Chapter Number:
4
Chapter Name:
NumPy Basics: Arrays and Vectorized Computation

In [2]:
import numpy as np
my_arr = np.arange(1000000)

In [4]:
my_list = list(range(1000000))

In [6]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 14.9 ms


In [7]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 624 ms


A Multidimensional Array Object

In [8]:
data = np.random.randn(2, 3)
data

array([[ 0.18115016,  1.24809713, -0.6728444 ],
       [ 0.41361905,  0.10231163, -0.48265279]])

In [9]:
data * 10

array([[ 1.81150162, 12.48097131, -6.72844403],
       [ 4.1361905 ,  1.02311634, -4.82652793]])

In [10]:
data + data

array([[ 0.36230032,  2.49619426, -1.34568881],
       [ 0.8272381 ,  0.20462327, -0.96530559]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

In [13]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [14]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [17]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 4)

In [20]:
arr1.dtype


dtype('float64')

In [21]:
arr2.dtype

dtype('int32')

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.empty((2, 3, 2))

array([[[1.40969023e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.42413554e-306, 3.69776220e-062]],

       [[4.71369984e-090, 3.54008234e-061],
        [5.51293071e+169, 8.02997873e-042],
        [3.99910963e+252, 5.49746921e+170]]])

In [25]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Data Types for ndarrays


In [26]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [27]:
arr2.dtype

dtype('int32')

In [28]:
float_arr = arr2.astype(np.float64)

In [29]:
float_arr

array([1., 2., 3.])

In [30]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [31]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [32]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [33]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [34]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [35]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [36]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [38]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [39]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=uint32)

# Arithmetic with NumPy Arrays:

In [40]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [41]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [42]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [43]:
arr + arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [44]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [46]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])


In [47]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [48]:
arr2 > arr



array([[False,  True, False],
       [ True, False,  True]])

In [49]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [51]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])


# Slicing For 2d array

In [52]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [53]:
arr2[1, 1]

2.0

In [54]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr2d[0, 2]

3

Slicing For 3d array:

In [56]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [59]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

Indexing with slices:

In [61]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [62]:
arr2d[:2]


array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arr2d[1, :2]

array([4, 5])

In [64]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [65]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])